name: Gudak Camera
favicon: null
layout_spectrum: 0.51811
typography_spectrum: 0.7954
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3001907365396619
  lightness: 0.5681352354586124
  saturation: 0.5322082878556103
  rhythmicContrast: 0.9767358377575874
purpose: []
