typography_spectrum: 0.23873
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8125
  lightness: 0.9375
  saturation: 0.125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75991
analytics:
  google: null
  facebook: null
  twitter: null
name: Gudak Camera
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Print Share your dream
purpose: []
